import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import yaml from "js-yaml";
import type { VariableResource, TrafficProfile } from "../types.js";

const YAML_PATH = "cost-profile.yaml";

export async function readCostProfile(): Promise<TrafficProfile> {
  if (!existsSync(YAML_PATH)) return {};
  const content = await readFile(YAML_PATH, "utf-8");
  const parsed = yaml.load(content) as { traffic_profile?: TrafficProfile } | null;
  return parsed?.traffic_profile || {};
}

export async function writeCostProfile(profile: TrafficProfile): Promise<void> {
  const header = `# Generated by slate
# Run: npx slate estimate
# Last generated: ${new Date().toISOString().split("T")[0]}
#
# ──────────────────────────────────────────────────────────────
#  FILL IN WHAT YOU KNOW. LEAVE BLANK WHAT YOU DON'T.
#  Empty fields produce a min–max range in the cost table.
#  Run \`npx slate wizard\` to fill these in interactively.
# ──────────────────────────────────────────────────────────────

`;
  const content = yaml.dump({ traffic_profile: profile }, { noRefs: true, lineWidth: -1 });
  await writeFile(YAML_PATH, header + content, "utf-8");
}

export async function generateCostProfile(variables: VariableResource[]): Promise<TrafficProfile> {
  const existing = await readCostProfile();
  const profile: TrafficProfile = {};

  const serviceFields: Record<string, Record<string, null>> = {
    lambda: { invocations_per_user_per_month: null, avg_duration_ms: null },
    api_gateway: { calls_per_user_per_month: null, avg_response_size_kb: null },
    dynamodb: { reads_per_user_per_month: null, writes_per_user_per_month: null, avg_item_size_kb: null, storage_gb_per_1000_users: null },
    s3: { storage_gb_per_1000_users: null, put_requests_per_user_per_month: null, get_requests_per_user_per_month: null, data_transfer_out_gb_per_1000_users: null },
    cloudfront: { data_transfer_gb_per_1000_users: null, requests_per_user_per_month: null },
    cognito: { mau_percentage: null },
    sqs: { messages_per_user_per_month: null, avg_message_size_kb: null },
    sns: { notifications_per_user_per_month: null, delivery_protocol: null },
    step_functions: { executions_per_user_per_month: null, avg_state_transitions_per_execution: null },
    eventbridge: { events_per_user_per_month: null },
    secrets_manager: { api_calls_per_user_per_month: null },
  };

  for (const v of variables) {
    const fields = serviceFields[v.service];
    if (!fields) continue;

    const existingService = existing[v.service] as Record<string, unknown> | undefined;
    const merged: Record<string, unknown> = {};

    for (const [key, defaultVal] of Object.entries(fields)) {
      merged[key] = existingService?.[key] ?? defaultVal;
    }

    profile[v.service] = merged as Record<string, number | string | boolean | null | undefined>;
  }

  await writeCostProfile(profile);
  return profile;
}

export function countEmptyFields(profile: TrafficProfile): { empty: number; total: number } {
  let empty = 0;
  let total = 0;
  for (const service of Object.values(profile)) {
    if (!service || typeof service !== "object") continue;
    for (const val of Object.values(service)) {
      total++;
      if (val === null || val === undefined) empty++;
    }
  }
  return { empty, total };
}
